name: CI

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Setup .NET Core 7.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Test
      run: dotnet test --logger "trx" /p:CollectCoverage=true /p:CoverletOutputFormat=lcov 

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      if: success() || failure()
      with:
        name: test-results
        path: PkceChallenge.UnitTests/TestResults/*.trx

    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        file: './PkceChallenge.UnitTests/coverage.info'
        format: lcov